apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: airswagg
spec:
  project: default
  source:
    repoURL: 'git@yourgiturl/argocd-repo.git'
    path: helm-charts/airflow
    targetRevision: prd
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airswagg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
