defaultAirflowTag: "2.5.3-python3.8"
executor: "KubernetesExecutor"
extraSecrets:
  "{{ .Release.Name }}-example":
    useHelmHooks: false
    data: |
      AIRFLOW_VAR_HELLO_MESSAGE: "Hi!"

extraConfigMaps:
  "{{ .Release.Name }}-example":
    useHelmHooks: false
    data: |
      AIRFLOW_VAR_HELLO_MESSAGE: "Hi!"
