airflow:
  executor: "KubernetesExecutor"
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
    jobAnnotations:
      "argocd.argoproj.io/hook": Sync
  postgresql: # by default postgres shipped by the chart
    enabled: false
  data:
    metadataConnection:
      user: postgres
      pass: postgres
      protocol: postgresql
      host: airflow-poc-postgres-ha-postgresql.airswagg.svc.cluster.local
      port: 5432
      db: "airflow"
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
  #dags:  
    #gitSync:    
      #enabled: true    
      #repo: ssh://git@github.com:DO-2K23-26/airswagg.git
      #branch: test
      #rev: HEAD    
      #sshKeySecret: airflow-git-ssh-secret

postgres-ha: # HA postgres
  postgresPassword: "postgres"
  database: "airflow"
